### ISSUE TITLE
Prevent pause menu from interrupting network of online game

### ISSUE THREAD

**Issue by MaxCWhitehead** [fishfolk/jumpy#1001]
### Description

Right now the pause menu will stop running game session / network session runner, this can lead to timeouts / disconnects. Perhaps we should not pause the game when pause menu is open in online play, just let it keep running. 

Or could consider pausing for all players, but this is more complex + also may lead to frustration if game is repeatedly paused by other players. Rounds are fast / cheap so having other players keep going while in menu seems acceptable to me.

Somewhat related to https://github.com/fishfolk/jumpy/issues/994 (pausing may be used to repro this, but not direct / sole cause)

**Comment by erlend-sh** [comment]
Yeah, only pausing the single session seems best. We could still let the other players know that a player has paused, e.g. by showing a ⏸️ sign above their character. That way at least there’s a chance of fair play.

**Comment by MaxCWhitehead** [comment]
> Yeah, only pausing the single session seems best. We could still let the other players know that a player has paused, e.g. by showing a ⏸️ sign above their character. That way at least there’s a chance of fair play.

We could also allow pause for everyone as a custom lobby setting or something down the line maybe if desired.

**Comment by MaxCWhitehead** [comment]
This is fixed, pause in online now keeps game going in background + no longer disconnects network. On full disconnects players are now also notified / given button to leave game.
