### ISSUE TITLE
Rendering artifacts on edge of rope netting sprite

### ISSUE THREAD

**Issue by MaxCWhitehead** [fishfolk/jumpy#1014]
### Description

![image](https://github.com/user-attachments/assets/2fcf202c-c99b-4395-b702-356983228f21)

I have been seeing some thin black lines to the left of the rope netting. Might be related to texture sampling settings, or maybe with atlas?

EDIT:
It seems bevy defaults to nearest sampling which seems right. It seems to flicker in and out as camera moves, wonder if we have mip maps and if that would help.

**Comment by MaxCWhitehead** [comment]
Seems like this can be fixed by disabling MSAA.

**Comment by MaxCWhitehead** [comment]
I think there are some other artifacts with pixels stretching/shrinking as the camera moves. Most notable at the tail end of smoothed movement when camera is settling down. 

On bottom right of map there is a thick vertical border on the blue/greenish tile:
![image](https://github.com/user-attachments/assets/a513f518-6686-46c6-803b-681977006a58)


If I move camera slightly to right, it shrinks again/shifts to other tiles:
![image](https://github.com/user-attachments/assets/58af3b08-7860-4a8a-8cdf-1146539c9373)

I wonder if should snap camera position to pixel grid - or if issue with screen resolution / pixel count / zooming camera.

**Comment by zicklag** [comment]
I think the shrink/shift thing is basically unavoidable with nearest-neighbor filtering unless we make sure we constrain zooms to a specific increment of physical pixels.

There are some related thoughts here: https://github.com/katharostech/bevy_retrograde/issues/51

**Comment by MaxCWhitehead** [comment]
Right that makes sense regarding zoom levels, probably not something we want to change.

**Comment by MaxCWhitehead** [comment]
Re-enabling msaa as I think the shimmering seems worse. The artifact here does rarely show up without AA, so changing that doesn't seem like the fix anyway.

**Comment by zicklag** [comment]
There's a possibility this could be related to texture atlas bleeding like https://github.com/forbjok/bevy_simple_tilemap/issues/4#issuecomment-1167685856, but I'm not sure.

It's a problem that's plagued me and even Bevy: https://github.com/bevyengine/bevy/issues/1949

I did figure out how to fix it, but this _might_ be a different issue.

It kind of lines up, though, because the bleeding issue tended to depend a lot of drivers/random nuances.

**Comment by MaxCWhitehead** [comment]
That definitely seems like a potential cause - glad you have done some digging on this in the past. Maybe we take a dive on this after we make rendering changes in bones, might be easier to troubleshoot and experiment with the shaders / render pipeline settings a bit less deep in engine.
