### ISSUE TITLE
can't start: invalid surface

### ISSUE THREAD

**Issue by JeromeSchmied** [fishfolk/jumpy#1026]
### Description

app doesn't start

### Log Messages

```
2024-09-11T17:43:25.340730Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux  Arch Linux", kernel: "6.10.9-arch1-2", cpu: "11th Gen Intel(R) Core(TM) i3-1125G4 @ 2.00GHz", core_count: "4", memory: "7.5 GiB" }
2024-09-11T17:43:25.376602Z ERROR log: surface configuration failed: incompatible window kind
thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:734:18:
Error in Surface::configure: Validation Error

Caused by:
    Invalid surface
```

**Comment by MaxCWhitehead** [comment]
Thanks for the report! will look into this.

**Comment by zicklag** [comment]
@JeromeSchmied do you know whether or not you're using Wayland or X11?

**Comment by MaxCWhitehead** [comment]
Another question - do you know if you have vulkan graphics drivers installed? 

(Some info here on that for arch, package depends on if you have Nvidia / AMD gpu or intel.): https://wiki.archlinux.org/title/Vulkan

Normally logs would show graphics card info - but it seems to have failed before making it this far, wonder if we can improve this and gather GPU / graphics backend info earlier?

**Comment by JeromeSchmied** [comment]
> @JeromeSchmied do you know whether or not you're using Wayland or X11?

yup, it's Wayland, `sway`

**Comment by JeromeSchmied** [comment]
> Another question - do you know if you have vulkan graphics drivers installed?
> 
> (Some info here on that for arch, package depends on if you have Nvidia / AMD gpu or intel.): https://wiki.archlinux.org/title/Vulkan
> 
> Normally logs would show graphics card info - but it seems to have failed before making it this far, wonder if we can improve this and gather GPU / graphics backend info earlier?

I have intel, I've had no vulkan, installed it now it works

**Comment by zicklag** [comment]
Sweet!

I'm surprised it didn't automatically fall back to OpenGL, which we should work fine with.

We might want to double-check to make sure we are enabling the OpenGL backend.
