### ISSUE TITLE
Add remappable controls

### ISSUE THREAD

**Issue by PotatoTech** [fishfolk/jumpy#139]
Currently, the controls for the game are hardcoded. It would be nice to allow players to remap both the menu and in-battle controls. Some possible methods are:

- [ ] Using an environment variable
- [ ] Reading from a config file
- [ ] Using an in-game menu

**Comment by olefasting** [comment]
I propose that we create this using a config file, for the time being, as I want to do a major effort to unify the UI, so creating a UI for this will probably just be a duplication of effort, at this point.
There will be a lot of methods and builders for creating more unified UI elements in the editor PR that is coming soon, and it will probbably be best to use these to (re)build all the games UI, as it will ensure that everything we create follow the same design guidelines

**Comment by zicklag** [comment]
This is fixed by the Bevy rewrite which comes with a control settings UI. The UI still needs some outstanding bugs fixed, but those are individual issues.
