### ISSUE TITLE
[SPEC] Periscope Rifle

### ISSUE THREAD

**Issue by SirGiraffey** [fishfolk/jumpy#151]
![Periscope Rifle](https://user-images.githubusercontent.com/57463655/135750095-8351fd3b-9b5d-482b-a847-d62246639300.png)

**Comment by erlend-sh** [comment]
This merits a new Item Extension System.

Various light to medium sized weapons could attach this in order to mod their weapon’s projectile exit.

**Comment by SirGiraffey** [comment]
Oh, great idea! Some ideas of attachments that came to my mind: e.g makes the gun perfectly accurate, make it kick up after each shot or make the bullets bounce from walls.
The editor should have an option to spawn items that are already upgraded with chosen extensions.

**Comment by olefasting** [comment]
Basically, a [trench rifle modification](https://www.alloutdoor.com/wp-content/uploads/2015/11/periscope-trench-rifle-01.jpg)

**Comment by SirGiraffey** [comment]
![obraz](https://user-images.githubusercontent.com/57463655/141011636-5dc2f6ad-967e-40e9-af77-75981004dd0c.png)
I was thinking more of a submarine periscope design

**Comment by zTecna** [comment]
![periscope rifle](https://user-images.githubusercontent.com/98235607/162029531-9755f323-a9f0-4d10-9e07-72bc8423136e.png)

**Comment by zicklag** [comment]
Re-opening to track the port to the latest version of the game.

**Comment by MaxCWhitehead** [comment]
@zicklag This was implemented in #953 / unless I missed something here :)

**Comment by zicklag** [comment]
Whoops! Awesome. :)
