### ISSUE TITLE
Track: Level Editor

### ISSUE THREAD

**Issue by olefasting** [fishfolk/jumpy#160]
This issue is created to keep track of the progress of the level editor, as well as outlining the process of contributing to this part of the development.

# Things that needs to be done

- [x] Placement of objects (weapons, pickups, decoration and environment items, like sproingers)
- [x] Option to import tilesets from existing maps
- [x] Background support (must be added to the `Map` struct and either added to the map draw method or exposed to `SceneRenderer`, which is currently handling the parallax backgrounds)
- [ ] Design and implementation of a gamepad controller scheme
- [x] Tool icons for the `ToolSelectorElement` (see #167, handled by @PixelFrog123)
- [ ] Autotiling (see #203)
- [ ] Add gamepad navigation support to `Window` (primarily navigation of the button area, for now)

# API Overview

The API is now, more or less, finalized and contributions will typically consist of implementations of the traits outlined below:

## EditorAction and UndoableAction

The enum `EditorAction` in the `editor/actions` module holds most possible actions taken within the bounds of the editor. Exceptoins are actions that happen in a very localized manner, inside the editor node, as the main purpose of this enum is to be able to return actions to be performed from UI and `EditorTool` implementations. Furthermore, all actions that modify map data, have to be implementations of the `UndoableAction` trait (also in the `editor/actions` module). These are actions with an `apply` and an `undo` method, that, in the case of the former, applies an action and in the case of the latter, completely reverses the changes made by the `apply` method. This means that if you, for example, change a tile in such an implementation, you will also have to store the old value of the tile, as well as any other data necessary, in order to reverse the action taken. All applied `UndoableAction` implementations are kept in a `History` struct, on the `Editor` node, within two stacks, one for applied actions and one for undone actions. This means that you do not need to consider anything happening outside of the confines of what your action does, as it will never be undone or redone, without any actions applied after the fact, also being undone or redone.
The API is modeled so that only the `apply` method on the `History` struct ever has mutable access to the `Map` instance (also held on `Editor`), so there is no real way to modify the map, outside of implementations of `UndoableAction`.

Actions are the primary means of making things happen in the editor and they are the return value of both `EditorTool` implementations and of GUI draw methods.

If more than one action is required to do what you want to do, it is possible to batch actions with `EditorAction::Batch` (easily constructed by calling the `EditorAction::batch` constructor) 

## EditorTool

The trait `EditorTool`, found in the `editor/tools` module is implemented for any tools that are to be used within the editor. This has to be instantiated and added to the static directory of tool instances with the `add_tool_instance` function, also found in `editor/tools`. Any tool that should be available in the tool selector toolbar (left toolbar), must also be added to this element upon construction. Both things are done in the constructor of the `Editor` node. This has been separated because of flexibility and separation of concerns. Maybe we want to have multiple ways of selecting tools in the future, so holding all of them in the toolbar element, wasn't a good idea, as I saw it. Toolbar elements shouldn't really hold such responsibilities, either, in stead being passive views into data fetched from context and map data, provided by their draw method (more on `ToolbarElement` implementations below..). The `EditorTool` trait has a `get_action` method that needs to be implemented, which will use the `EditorContext` and the current state of the map to determine what `EditorAction` should be returned and applied, upon clicking the left mouse button, or in the case of a gamepad, some undetermined primary action button. 

It is also possible to make a tool only be available when certain criteria are met by implementing the traits `is_available` method (return `false` to disable it). Currently, this just hides the tool from the `ToolSelector` toolbar element but this behavior will probably be changed for some kind of greyed out disabled button, in the future.

## ToolbarElement and Window

Implementations of `ToolbarElement`, found in the `editor/gui/toolbars` module, will be the primary way of expanding on the UI. They are held by a `Toolbar` (add them to the `Toolbar` upon creation, in the `Editor` node constructor) and they are meant to display data and controls, like buttons, based on the context and map data they receive as parameters of their `draw` method. The method also returns an `Option<EditorAction>`, which can be used to return the result of a button press or something similar.
The `draw` method also has a `size` parameter, which is the size of the UI `Group` that holds the element, minus margins only on the side that doesn't border the screen edge, where this applies. This was done so that scrollbars for elements would be flush against the screen edge, even when there were margins applied to the element. It is therefore up to the developer to adhere to the `size` parameters x value, both in terms of margins as well as because there is no horizontal scrolling in macroquads UI.
Any overflow on the y-axis, will result in vertical scrolling being enabled for the element. You can also add a button bar, to the bottom of your element, by implementing the `get_buttons` method. This also requires that you set the `has_buttons` member of the `ToolbarElementParams`, returned by `get_params`, to `true`, as buttons will just be ignored, if this is set to `false`.

Implementations of the `Window` trait should be used for all windows opened by the editor, in cases where you, for example, want to construct a new object or something like this. When adding a window implementation, you should also add an appropriate action to open this window in the `EditorAction` enum. To close a window, you just apply a `EditorAction::CloseWindow` action, with its `TypeId` as a parameter (use `TypeId::of::<T>()` to get this value). The `draw` method of the `Window` trait will return an action, just like `ToolbarElement` implementations and you can also add buttons with actions, by implementing the `get_buttons` method. For submit-actions, for example, you would therefore make a batch containing the action to be taken, as well as an `EditorAction::CloseWindow` action, to close the window. Buttons on the bottom of the window should be implemented using the `get_buttons` method, to ensure a uniform layout, across the project. As with `ToolbarElement`, you will have to set the `has_buttons` member of the `WindowParams`, returned by `get_params`, to `true` for these buttons to be drawn....

## Examples

I am not including examples here, as there are good example implementations of all these traits already in the code base. Check out the sub-modules of the modules that hold the traits for example implementations....

If you have any questions or comments, feel free to share them by posting them here or by contacting me on Discord....

**Comment by zicklag** [comment]
Since the Bevy rewrite the editor has been re-worked. I'm closing this in favor of specific issues for remaining tasks.
