### ISSUE TITLE
Animated emotive reactions

### ISSUE THREAD

**Issue by erlend-sh** [fishfolk/jumpy#183]
@PixelFrog123 clearly demonstrates such a system in one of his asset packs:

![](https://img.itch.zone/aW1hZ2UvNDk4MTk0LzI1NzYzMTQuZ2lm/original/kVnyY1.gif)

We wanna have a system just like this. If an explosive comes close to a character, it should *emote* in the form of:
1. a change in facial expression (to state: shocked)
2. a dialogue bubble

**Comment by erlend-sh** [comment]
Update from @zTecna:
![0B2D9B08-D60A-4428-BBEE-1630F7C3BDE1](https://user-images.githubusercontent.com/583842/161227512-84ad9c7e-d38c-4aab-9ebf-0b7780f9a6fb.png) ![F5927B23-D44F-4B24-94AD-A3ED78B78C8A](https://user-images.githubusercontent.com/583842/161227505-497652e5-bb91-473a-857d-ce57fdb3ec04.gif)

**Comment by zicklag** [comment]
@zTecna you don't happen to have the body animation without the faces on it do you? If not, my brother @harsulinsghost can work on that, but he wanted to make sure that you didn't already have something.

**Comment by zTecna** [comment]
here
https://drive.google.com/drive/folders/1yiKbkFtIL-AIPsrgAE-Rh7Q41N45wiTv?usp=share_link

**Comment by zTecna** [comment]
![lionfishy eyeless](https://user-images.githubusercontent.com/98235607/214641520-5f7fe887-a98b-4aa3-87c6-7d18c9e289d1.png)
![fishy eyeless](https://user-images.githubusercontent.com/98235607/214641523-d9e22b8b-e5fd-44ce-abe2-4374bba6b11b.png)
![catty eyeless](https://user-images.githubusercontent.com/98235607/214641524-39222def-4a73-45a1-b2b8-67c776fd0106.png)
![sharky eyeless](https://user-images.githubusercontent.com/98235607/214641527-a4c8b6a6-26d1-41c6-b748-6b1e0507d3c0.png)
![pescy eyeless](https://user-images.githubusercontent.com/98235607/214641530-b89fc86c-e0d4-4cee-a774-b4ba65bf5cb3.png)
![orcy eyeless](https://user-images.githubusercontent.com/98235607/214641532-69559c95-e889-4191-98da-9198fe90e75d.png)
I saw it here and I only removed the ones from the idle and walking animations but I think it already helps

**Comment by zicklag** [comment]
Thanks that's perfect!

I'm hoping to get this done along with the the separate fin control.

**Comment by zicklag** [comment]
Closed by #601.
