### ISSUE TITLE
Re-implement AI Fighters

### ISSUE THREAD

**Issue by billyb2** [fishfolk/jumpy#272]
**Edited by @zicklag:**

We need to re-implement AI fighters. There is currently no provision for AI players, so the field is wide open as for how to make it work.

As a first pass, it doesn't really matter that they be smart or difficult, but just enough that playing 1 player isn't 100% pointless.

---
**Original post:**
> The bots that currently exist in-game are decent to play against, though they aren't as smart as they could be. Bots that take better account of their environments, weapon\s in play, and positions of their opponents would make single player of the game much more fun.

**Comment by zicklag** [comment]
I've got WIP pathfinding in #587, which is a big first step. I'll try finishing that off, probably after getting #183 working.

**Comment by zicklag** [comment]
We've now got basic AI players following the main player relentlessly ( might need to tweak that ), and all I've got to is give them swords and make them swing it when they spawn to finish this up for the MVP.
