### ISSUE TITLE
Cleanup of systems

### ISSUE THREAD

**Issue by olefasting** [fishfolk/jumpy#329]
**NOTE:** Now that we have the engine-core project to take into consideration, we should design these systems with separation of fishfight-specific implementation and more general implementation, the latter belonging in core.

As I mentioned in the PR for the ECS refactor, the systems are a bit messy at the moment, as I was focused on code reuse to reduce development time. This does not affect performance or stability in any way, as far as I know, but it would be nice to do some more refactoring here to better separate code by concern.

I will take care of this as I go along with networking etc, so this issue is created mostly as a way to keep track of this progress and to signal that this is an issue we are aware of, to anyone browsing the repository. This isn't to say that someone other than me shouldn't try to handle this -- if you have the time and the know-how, be my guest -- but if no one else does it, I will do it over the next releases...

Primarily, we need to do some refactoring of what is now `update_player_state`. This should really just be handling state transitions but it is now also handling some of the integration by applying velocities based on controller state and player state. This is very messy, imo.

~~The `PlayerState` component could also use some love. We should be changing some or all of the `bool` flags to enums, for example.~~ **Done**

**Comment by zicklag** [comment]
This is out-of-date after the Bevy rewrite.
