### ISSUE TITLE
Rendering issues on OpenGL backend

### ISSUE THREAD

**Issue by olefasting** [fishfolk/jumpy#424]
There is an issue when enabling egui (egui_glow) with the new OpenGL backend, where white artifacts appear around the player sprites. It also makes all the glyphs rendered with glyph brush white squares.

As our renderer is very simple and because this issue causes geometry from glyph brush to glitch, as well, I think it is safe to assume that the issues lie in how egui_glow handles its draw calls (lack of sanitation?).

**Comment by zicklag** [comment]
This is out of date after the Bevy rewrite.
