### ISSUE TITLE
Texture Sampling Bleeding

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#446]
This is probably not going to be an issue with the renderer rework, but if we want to do a release before the renderer rework is done, then it could be good to fix the bleeding that can be seen for the animated decorations:

![image](https://user-images.githubusercontent.com/25393315/173883473-0b5f5c09-0966-41fe-8f11-05afb4460179.png)

I've been plagued by this in my own projects, many a time, but I think it could be somewhat simple to remedy. I've found that reducing the UV along the edges just slightly can keep the sampler from sampling into the next tile and causing the artifacts.

**Comment by zicklag** [comment]
After the bevy rewrite I've still noticed a little bit of this issue.

This should be exactly related to this Bevy issue ( https://github.com/bevyengine/bevy/issues/1949 ), and I've been able to fix it for a couple tilemap rendering plugins in Bevy, so hopefully I'll be able to fix it in Bevy sprite rendering, too.

**Comment by selfup** [comment]
Glad to see there has been progress on this! Thank you for keeping track of it

**Comment by zicklag** [comment]
I'm not seeing this happen anymore. I'm not sure if it's been fixed somehow or if things just might have been tweaked to prevent it from happening. I'm going to close this for now, but if it happens again, we can re-open.
