### ISSUE TITLE
Update Music & Play Specific Music on Different Menus/Screens

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#494]
Here's our music list:

![image](https://user-images.githubusercontent.com/25393315/204570074-c885670c-ecb1-46d8-aeb2-d54f9e60af73.png)
![image](https://user-images.githubusercontent.com/25393315/204570093-eb9b9e18-32d7-445f-9b8b-7307c49476b0.png)

We already have the music in the [music folder](https://github.com/fishfolk/jumpy/tree/main/assets/music), but we need to rename them match the list above.

Then we just need to update the game to select appropriate music when going to different menus or starting a fight, etc.

**Comment by erlend-sh** [comment]
[fish-folk_ogg.zip](https://github.com/fishfolk/jumpy/files/10899909/fish-folk_ogg.zip)
[fishfolk-mp3-p1.zip](https://github.com/fishfolk/jumpy/files/10899918/fishfolk-mp3-p1.zip)
[fishfolk-mp3-p2.zip](https://github.com/fishfolk/jumpy/files/10899932/fishfolk-mp3-p2.zip)
