### ISSUE TITLE
GLIBC Not Found For Release Build

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#509]
I'm getting an error trying to run the release build of Jumpy on my Linux machine:

```
./jumpy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./jumpy)
./jumpy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./jumpy)
./jumpy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./jumpy)
./jumpy: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./jumpy)
```

I think there was a recent build that wasn't doing this. A couple of thoughts:

- Maybe it's because a GitHub runner updated the software versions on it, and now it's requiring a newer version of glibc than I have on my machine? I don't update that often 'cause I'm not root on my machine.
- Maybe it's because I added the mimalloc library as the Rust global allocator?

@orhun I'm wondering if you've ever seen something like this, because you've done more with the CI I than I have.

**Comment by zicklag** [comment]
Because I can compile it on my machine and not run into issues I think it must be specific to being built on the GitHub runner.

I'm not super familiar with GLIBC or how we might be able to make it use an older version.

It [looks like](https://users.rust-lang.org/t/how-to-change-rust-glibc-version/71183/2?u=zicklag) we'll have to use Docker to build with an older GLIBC.

**Comment by orhun** [comment]
Normally we shouldn't build with an older version of `glibc`. Can you share more information about your setup e.g. distribution, `glibc` version etc. so that I can look into other possible solutions?

**Comment by zicklag** [comment]
I'm not 100% sure how to tell which `glibc` I have, but from the `glibc-source` in my package repo, it looks like I have `2.31`.

I'm on Pop!_OS 20.04. If we don't want to build with an older `glibc`, the right solution is probably just for me to update my system.

I'll try to do that once I get the chance.

**Comment by orhun** [comment]
> the right solution is probably just for me to update my system.

Yup, sounds correct.

**Comment by zicklag** [comment]
OK, I'll close, then, because it's just my issue.
