### ISSUE TITLE
Set Game Fixed Update Frames to 60 FPS

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#544]
Currently the game runs at a 45 fixed updates-per-second. We want to change this to 60 FPS.

The original reason for turning it down to 45 was for performance in the networking rollback mode, but since networking isn't working without desync bugs right now anyway, we may as well let the local play experience be as good as it can be, and fix the networking later, once we have the new ECS model in place that should fix the desync bugs.

---

This should be a simple change. The first step is to change this constant to 60:

https://github.com/fishfolk/jumpy/blob/4a8c0bd0687363e9b2e7628d7d80a1fa7f428146/src/main.rs#L78

At that point, most of the physics will seem to run in fast-forward, because all the other game constants are tuned for running at 45 FPS right now.

That means the last step is to go and update all the constants regarding player movement/fall speed, etc.

The item constants, such as fuse times, etc will be found in this asset folder: [`assets/map/elements/item`](https://github.com/fishfolk/jumpy/tree/main/assets/map/elements/item).

There may also be some constants in the [player states](https://github.com/fishfolk/jumpy/tree/main/src/player/state/states) and the [item Rust implementations](https://github.com/fishfolk/jumpy/tree/main/src/map/elements).

Pretty much you just have to tweak those numbers until it plays normal again at 60 FPS.

**Comment by Rishav1707** [comment]
![Small](https://user-images.githubusercontent.com/97666287/210127270-80997d68-abfa-4e63-876e-e3420dbee36a.png)

Only this constant you want to change?

**Comment by zicklag** [comment]
> Only this constant you want to change?

There's at least one other constant [here](https://github.com/fishfolk/jumpy/blob/4a8c0bd0687363e9b2e7628d7d80a1fa7f428146/src/player.rs#L339), but we try to keep constants out of Rust code, so that might be the only other Rust one.

Most of them should be in asset YAML files, like here:

https://github.com/fishfolk/jumpy/blob/4a8c0bd0687363e9b2e7628d7d80a1fa7f428146/assets/default.game.yaml#L3-L6

And in items, like this:

https://github.com/fishfolk/jumpy/blob/4a8c0bd0687363e9b2e7628d7d80a1fa7f428146/assets/map/elements/item/grenade/grenade.element.yaml#L3-L7

We'll need to adjust those constants related to timing, such as the fuse time and the throw velocity, in all the items.

**Comment by zicklag** [comment]
I'm fixing this as a part of #541 .

**Comment by zicklag** [comment]
Finished in #541.
