### ISSUE TITLE
Collision Detection Improvements

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#552]
With the new sword juicing, we run into a scenario where our collision detection doesn't really shine because we only support non-rotated, rectangular collision boxes.

This causes problems right now because the sword will kill you as it falls, even if it visually doesn't touch you, because the sword is visually rotating, but not really rotating in the physics simulation.

Something I think is worth considering is using [Parry](https://www.parry.rs/) for collision detection, while still using our own physics engine for movements. That way we can do collision detection on things like the sword, that accurately takes into account its rotation, but we still get our nice and snappy physics and we don't have to change anything other than how we tell when two things are in contact.

It would be an un-noticeable, low-impact change to to try out, and _might_ increase performance/reliability in our collision detection. I know there were a few glitches, for instance, in our current implementation, if you had non-even numbered widths or heights for collision shapes. We also don't have circle colliders yet, which would be useful for explosions.

The physics system is really simple already so it should be relatively simple changes to just a small piece of the game code.

If anybody has thoughts feel free to chime in!

**Comment by erlend-sh** [comment]
I think @not-fl3 figured out a way to do this with our basic physics system, but I'm not opposed to pulling in Parry for collision detection. Your call!
