### ISSUE TITLE
Port Items To `bones_ecs`

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#554]
With #541 merged, we now have to migrate the items from before the merge to `bones_ecs`.

We need to take the items from [here](https://github.com/fishfolk/jumpy/tree/e00bd2f279b49c0cbf674e77db1747774f445300/src/map/elements) in the old commit in Jumpy to their new home [here](https://github.com/fishfolk/jumpy/tree/main/core/src/elements) in `jumpy_core`.

Give a shout out if you want to work on one of these, and I'm often available on chat to help with any questions:

- [x] grenade https://github.com/fishfolk/jumpy/pull/565
- [x] kick_bomb #568
- [x] mine https://github.com/fishfolk/jumpy/pull/617
- [x] stomp boots #595
- [x] crab https://github.com/fishfolk/jumpy/pull/567
- [x] crate https://github.com/fishfolk/jumpy/pull/607#event-8452117781

**Comment by zicklag** [comment]
I'll start on grenades next.

**Comment by lecoqjacob** [comment]
I’ll take the crab.

**Comment by lecoqjacob** [comment]
Picking up kick bomb

**Comment by legendiguess** [comment]
I gonna reimplmenet stomp boots 👢

**Comment by erlend-sh** [comment]
Recent docs (url will probably change soon):
https://fishfolk.org/games/jumpy/developers/creating-items-and-elements/
https://fishfolk.org/bones/overview/introduction/
https://fishfolk.org/bones/ecs_tutorial/the-basics/
https://fishfolk.github.io/bones/rustdoc/bones_lib/index.html

**Comment by ThousandthStar** [comment]
I think I can do the crate.

**Comment by zicklag** [comment]
This is done now! Thank you so much everyone!
