### ISSUE TITLE
Re-implement Cannon

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#576]

**Comment by Zac8668** [comment]
I'm working on this.

**Comment by Zac8668** [comment]
@zicklag About the projectile of the cannon, we probably should make it shoot a lit Kick Bomb right? So that in the assets we can just reference a Kick Bomb that is already "added"

**Comment by zicklag** [comment]
Yeah, I think it can just be a kick-bomb. But I think it exploded on contact, instead of bouncing around. The asset should work fine for it.

**Comment by DRuppFv** [comment]
I'm currently working on the cannon and want your opinion on the cannonball.

I feel torn between adding new fields to the lit kickbomb, as `explode_on_contact: bool` (and probably some others that will be necessary) and using it as the cannonball, or creating a completely new item with `lit` state only. What do you think?

**Comment by zicklag** [comment]
Honestly, I could be fine either way, but I'm leaning towards adding more fields to the kickbomb. I like that because it puts more power in YAML for re-using the bomb in other scenarios, which seems like it'd have modding value.
