### ISSUE TITLE
Re-implement Map Editor

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#620]
We need an MVP of the map editor working so we can get the maps polished.

**Comment by SirGiraffey** [comment]
![ryby walka](https://user-images.githubusercontent.com/57463655/221418505-77e59acf-a981-4c33-9898-58eda3efa310.png)
The tilemap is not showing up for me regardless of clicking the tools on the top left or pressing left-right-middle mouse buttons or changing layers

**Comment by zicklag** [comment]
Oh, that's not right, I'll look at that now.

**Comment by SirGiraffey** [comment]
[Tilemap Assets.zip](https://github.com/fishfolk/jumpy/files/10833988/Tilemap.Assets.zip)
Here are also the assets with the rock, metal and wood tilemaps along with ship decorations
![Ground Metal](https://user-images.githubusercontent.com/57463655/221419074-5c0ed5ba-cb21-4b3c-8cc8-27b200dda78d.png)
![Ground Rock](https://user-images.githubusercontent.com/57463655/221419075-47afac30-cda7-4200-a919-683f82164b5f.png)
![Ground Wood](https://user-images.githubusercontent.com/57463655/221419077-8fd6f6e2-638c-4b6c-8115-85119ffc653e.png)
![Ship Decorations](https://user-images.githubusercontent.com/57463655/221419078-27c19fb9-1358-4714-ba11-74cd958c740e.png)

**Comment by zicklag** [comment]
This should be done now! We can open up new issues for specific editor features, but it's close enough for the MVP.
