### ISSUE TITLE
Fix Warnings in Console on Game Startup

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#713]
When starting up, the game puts out a set of warnings:

```
Attempt to override an existing message: "move-up".
Attempt to override an existing message: "move-down".
no `AssetLoader` found
```

The first two are due to two our `.ftl` translation assets files defining `move-up` and `move-down`. We should find the duplicate entries and remove them.

The asset loader warning is going to be harder to find. I think it has something to do with loading map assets. There is probably a map somewhere that references an asset with an extension that doesn't have an asset loader or something like that. The interesting part is that apparently we don't _need_ whatever asset isn't working, because I've never noticed anything missing.

**Comment by lecoqjacob** [comment]
I'll pick this up. Should be super quick for me to clear off the board
