### ISSUE TITLE
Kick Bomb Bounce Is Unpredictable

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#720]
@erlend-sh What is the logic supposed to be as far as when the kick bomb should bounce off of the player and when it should kill them.

Right now the behavior seems kind of hard to predtict ( I'm not sure why yet ) but I don't know how it's supposed to be.

**Comment by erlend-sh** [comment]
The original design intended for it to be less bouncy, just rolling along the ground, sort of bomberman style. Maybe we can try that again?

The timer needs to be much shorter. And I think it should only take two kicks; I’m the third it will explode. So, either it explodes by timer, or by 3rd kick.

**Comment by nelson137** [comment]
If @n16hth4wkk isn't still working on this I would like to take a shot at implementing Erlend's suggestions

**Comment by n16hth4wkk** [comment]
@nelson137 give it a go :) I have code on a branch but it's old

**Comment by nelson137** [comment]
Thanks!

**Comment by nelson137** [comment]
Currently the kick bomb will always explode if it hits the back of a player. Is that still desired behavior?
