### ISSUE TITLE
Grenades That Explode While You Hold Them Fly Out of Your Hand Instead of Despawning

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#723]

**Comment by lecoqjacob** [comment]
Ill take this

**Comment by zicklag** [comment]
Awesome. Just a warning, @TekhnaeRaav tried to look at this at some point and thought it might have beena weird ordering thing with Bones, or maybe something like the fact that a component was reading stale data, along the lines of https://github.com/fishfolk/bones/issues/96 or https://github.com/fishfolk/bones/issues/82.

I haven't looked at it yet, so I'm not sure, but it's something to keep an eye out for.
