### ISSUE TITLE
Throwing a Crate Up Should Be Able to Bonk Yourself If You Don't Move.

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#731]
We might need to do something like an "arm delay" so that you can't hurt yourself with the crate, until a split second after it's thrown.

**Comment by lvllvl** [comment]
I was looking around in the codebase, does this issue entail changing:

* `core > elements > crate_items.rs`
    + `fn update_thrown_crates`

Does `core>src> damage.rs` also get updated in this?

When a box hits the top of a player's head, does it cause damage? Or kill the player? Or does the box just break and respawn?

**Comment by zicklag** [comment]
> changing... `fn update_thrown_crates`

Yeah, the key line is this one here:

https://github.com/fishfolk/jumpy/blob/b22603540980b702212fbfa1b3601cb5dfeb0532/core/src/elements/crate_item.rs#L218

Where it makes sure `e != thrown_crate.owner` is how it makes sure it doesn't damage the person who threw the crate. We need to make sure that the crate kills the player if it hits them out of mid-air, but doesn't kill them immediately when they throw it out of their hands.

We don't need to change `damage.rs`. When it hits the players head it kills theplayer, and the box breaks and re-spawns.
