### ISSUE TITLE
Add `ElementKillCallback` components for items and critters.

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#774]
With #773 we now have a way to gracefully cleanup elements such as crabs and items that have been spawned, so that when we delete them in the editor, they are removed from the map without having to click "Reload".

See the PR for more details if you want to implement, and comment if you have questions!

**Comment by AustinHellerRepo** [comment]
I'm going to work on this next. Thanks for your help with the previous PR, @zicklag.
