### ISSUE TITLE
Rescaling the window makes the controller input settings panel get stretched

### ISSUE THREAD

**Issue by metasyn** [fishfolk/jumpy#783]
Here is what It looks like when I open the app:

![image](https://github.com/fishfolk/jumpy/assets/1719730/74e0ce51-8d36-48e6-a880-258f04a9cb02)

Then I make it a little wider

![image](https://github.com/fishfolk/jumpy/assets/1719730/0c18518f-54be-46e2-9e70-9612d48cf1d3)

But going smaller kinda messes up the right side?

![image](https://github.com/fishfolk/jumpy/assets/1719730/96520a36-913d-4948-bd38-9f171bf0dbaf)

Lets go big again

![image](https://github.com/fishfolk/jumpy/assets/1719730/8b0a7f5b-986c-4af6-bf36-d2386984809f)

Then if you kind of move it vertically at all it makes it stretch out even more

![image](https://github.com/fishfolk/jumpy/assets/1719730/8b21e820-94be-4729-875c-c831b20d333d)

Anyway, just a little bug. I'm running Linux (Pop!_OS 22.04) on [nightly-2023-05-25](https://github.com/fishfolk/jumpy/releases/tag/nightly-2023-05-25)

**Comment by metasyn** [comment]
Game looks fun/cute by the way, stoked to try it out sometime with some friends sometime.

**Comment by zicklag** [comment]
Got this fixed! Thanks for the report!
