### ISSUE TITLE
ARM64 Linux build

### ISSUE THREAD

**Issue by alberic89** [fishfolk/jumpy#788]
Is it possible to obtain an aarch64 linux build ?
Thank you !

**Comment by zicklag** [comment]
Hey there! I think that's doable, but I haven't tested that yet so I'm not 100% if we'll run into issues or not. If anybody want's to attempt to add ARM builds to our CI that would be appreciated!

**Comment by alberic89** [comment]
I have tested to build on a Raspberry Pi 4 with `cargo run`, but I have the following error:

```
    Finished dev [optimized + debuginfo] target(s) in 0.92s
     Running `target/debug/jumpy`
2023-05-31T18:20:58.261619Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
thread 'main' panicked at 'Unable to find a GPU! Make sure you have installed required drivers! For extra information, see: https://github.com/bevyengine/bevy/blob/latest/docs/linux_dependencies.md', /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_render-0.9.1/src/renderer/mod.rs:121:10
```
I have also tried to add a aarch64-unknow-linux-gnu target to release workflow, but I get the error:
```
Error: failed to run custom build command for `libudev-sys v0.1.4`
Caused by:
  process didn't exit successfully: `/home/runner/work/jumpy_arm/jumpy_arm/target/release/build/libudev-sys-596e66ad3ed6d168/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBUDEV_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "pkg-config has not been configured to support cross-compilation.\n\nInstall a sysroot for the target platform and configure it via\nPKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a\ncross-compiling wrapper for pkg-config and set it via\nPKG_CONFIG environment variable."', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libudev-sys-0.1.4/build.rs:38:41
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```

**Comment by zicklag** [comment]
> I have tested to build on a Raspberry Pi 4 with cargo run, but I have the following error:

Ah, that might be fixable.

Try running it like this:

```
WGPU_BACKEND=gl cargo run
```

**Comment by orhun** [comment]
I wanna take a crack at this @zicklag, feel free to assign it to me :3

**Comment by zicklag** [comment]
Awesome!

As a hint for something we might need to change in the game, I think we'll need to add the `Gl` backend to the [`WgpuSettings`](https://docs.rs/bevy/latest/bevy/render/settings/struct.WgpuSettings.html#structfield.backends) to allow it to fallback to the OpenGL backend when nothing else is available, without requiring the `WGPU_BACKEND=gl` environment variable.

By default, since not everything is supported on Gl, Bevy won't automatically revert to it, IIRC.

**Comment by alberic89** [comment]
> Try running it like this:
> 
> ```
> WGPU_BACKEND=gl cargo run
> ```

I have tested, and the game works with use of `WGPU_BACKEND=gl`.

**Comment by zicklag** [comment]
@alberic89, @orhun just merged ARM64 builds, which should be automatically built in the next nightly release just 4 or 5 hours from now I believe.

Also, the issue where you had to specify `WGPU_BACKEND=gl` appears to have been [fixed](https://github.com/bevyengine/bevy/pull/7481) after we upgraded to Bevy 0.10.

So I think Jumpy should run fine on a Raspberry Pi now! If you check out the [release list](https://github.com/fishfolk/jumpy/releases) tomorrow you should be able to test out the latest nightly and see if it works.

Feel free to re-open if you have more trouble!

**Comment by orhun** [comment]
ARM64 builds are there!

**Comment by alberic89** [comment]
All works fine!
