### ISSUE TITLE
Add Hats

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#804]
We already have player attachments, so attaching hats to the players should be very easy, but we will also need a UI for selecting your hat in the player selection screen.

**Comment by zicklag** [comment]
@erlend-sh what kind of user experience were you thinking for hats? I'm thinking of working on this next.

Should we just go with like a left and right arrow selection on the player select screen, that shows the hat in the player preview?

**Comment by erlend-sh** [comment]
Yeh, move automatically to hat selection after fish character has been selected.

**Comment by zicklag** [comment]
This has been implemented a while back now.
