### ISSUE TITLE
Mashing space on player other than player 0 in online game crashes

### ISSUE THREAD

**Issue by MaxCWhitehead** [fishfolk/jumpy#834]
### Description

In an online session with two clients, on character select screen, pressing spacebar many times on 2nd player crashes game, and 1st remains on a black screen.

### To Reproduce

1. Run two clients
2. Press 'Network Game' on main menu on each client
3. Select 'Online' on each client
4. Press 'search' on each client
5. Wait for match to switch to character select
6. Identity which client is player 0 and which player 1 (Player 0 should have < You > above 'Pick a fish'
7. On player 0 client ( < You > on left-most slot) press spacebar to lock in character.
8. On player 1 client, mash spacebar. (Press at least twice in rapid succession)

### Expected Behavior

Pressing spacebar should ready up the character on each client.

### Additional Context

I did not test this in LAN game as not sure how to get that to work. It seems this error is caused by subsequent presses of spacebar selecting the map, on non-player 0 clients, this menu seems to exist briefly before being removed. Pressing spacebar twice slowly on non-player 0 clients does not reproduce the issue.

### Log Messages

2023-07-08T06:23:46.784063Z  INFO jumpy::networking::online: Online match complete random_seed=17597830045416933290 player_idx=1 player_count=2
2023-07-08T06:23:46.791155Z  INFO jumpy::ui::main_menu::network_game: Starting network game player_idx=1
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Only player 0 may select the map.', src/ui/main_menu/map_select.rs:265:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (1)' panicked at 'A system has panicked so the executor cannot continue.: RecvError', /Users/max/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:194:60
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/max/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.10.1/src/task_pool.rs:376:49
thread 'Compute Task Pool (1)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/max/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_render-0.10.1/src/pipelined_rendering.rs:111:77
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/max/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.10.1/src/task_pool.rs:376:49

**Comment by zicklag** [comment]
Thanks for finding this! Fixed in https://github.com/fishfolk/jumpy/pull/836.
