### ISSUE TITLE
Objects Get Stuck in Walls, Especially Due to Rotation

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#853]
### Description

Sometimes objects will get stuck in walls, and just hang there. I don't think this used to happen like this, so I believe it was probably introduced in https://github.com/fishfolk/jumpy/pull/848, which avoided pushing things out of walls as often for performance's sake.

It is also possible to, very rarely, have the player get stuck in the floor, making it impossible to move.

### To Reproduce

An easy way to reproduce is to walk up to a wall and drop a musket while facing the wall.

### Expected Behavior

Items should get pushed out of walls by the physics system.

**Comment by MaxCWhitehead** [comment]
@zicklag I think this should be resolved, but can verify it looks as you expect / close this out.

**Comment by zicklag** [comment]
Yep, looks like it's working now!
