### ISSUE TITLE
Support setting a custom path for assets

### ISSUE THREAD

**Issue by orhun** [fishfolk/jumpy#865]
### Description

When I run `jumpy,` it looks for the `assets` in the current directory which prevents me from putting into another location (such as `/opt` which is needed for the Arch Linux package)

Can we potentially support an environment variable (`JUMPY_ASSETS`) for pointing out to an assets directory?

**Comment by zicklag** [comment]
Ah, yeah, I forgot about that! The feature was lost when we rewrote the asset server. It won't be hard to get that working.

**Comment by zicklag** [comment]
There we go! Merging a PR that adds support for the `JUMPY_ASSETS` and `JUMPY_ASSET_PACKS` environment variables.

We're not using asset packs in jumpy yet, and maybe we should just use the `directories` crate to find some user directory suitable for asset packs, but I added the var for asset packs for now, just in case.

**Comment by zicklag** [comment]
@orhun Are you ready for me to make an 0.8.2 release or should we wait to see if there are any other blockers first?

**Comment by orhun** [comment]
Just 🐑 it! Should be fine now.

**Comment by zicklag** [comment]
[Voilà! v0.8.2](https://github.com/fishfolk/jumpy/releases/tag/v0.8.2).
