### ISSUE TITLE
Steam Deck: Graphics scaled up too big

### ISSUE THREAD

**Issue by MaxCWhitehead** [fishfolk/jumpy#904]
The bevy_window crate computes scale factor in WindowResolution based on OS reported pixel density. This seems to not end up right on the deck. 

Setting scale_factor_override = 1.0 fixes graphics scaling issues on deck, from my research this is probably less of an issue with bevy's computation of scale factor and more that the deck doesn't report accurate values, but will look into it more.

Worse case scenario we have to detect steamdeck and adjust this value.

**EDIT:** The TLDR of my comments is that I think we should include some special launch shell scripts for linux distribution through steam. If using steam deck display, need to set a variable to fix scale. Doing this in shell / on game launch side keeps the options close to user, and doing this in engine / game code is harder and less accessible to tweak.

**Comment by zicklag** [comment]
Transferred to the Jumpy repo. 👍️
