### ISSUE TITLE
If player drops hat while translucent during invincibility, hat remains translucent

### ISSUE THREAD

**Issue by MaxCWhitehead** [fishfolk/jumpy#930]
### Description

If player drops hat while translucent during invincibility, hat remains translucent.

### To Reproduce

1. Spawn into game with hat
2. Press F to ragdoll self, dropping hat (this ragdoll feature is not implemented in this moment, PR coming soon, probably will be by the time someone is fixing this 😸 )
3. Observe hat is translucent and stays that way

### Expected Behavior

Hat should drop without being translucent.

**Comment by nelson137** [comment]
Could someone please assign this to me :)
