### ISSUE TITLE
Player Select: Last player readying up cannot choose hat in online play (match starts immediately)

### ISSUE THREAD

**Issue by MaxCWhitehead** [fishfolk/jumpy#963]
### Description

In online play, it seems hat is selected after readying up, if the last player hits ready, the lobby transitions to map select before player has opportunity to select hat. 

In local play, this is not an issue.

### Expected Behavior

Should move hat select before ready up?

**Comment by nelson137** [comment]
I agree that hat selection should be a step before being ready. I'm going to start work on this if there's no concern about this approach.

**Comment by MaxCWhitehead** [comment]
@nelson137 go for it, thanks!
