### ISSUE TITLE
Audio: Play sound on player death

### ISSUE THREAD

**Issue by MaxCWhitehead** [fishfolk/jumpy#986]
### Description

Would be good to have some audio feedback on player dying.

**Comment by reemhashir1** [comment]
My team and I are doing a software engineering project as part of a class at Carnegie Mellon University. Is this issue something we can work on? If so, could you please assign this to us? Thank you so much!


@elliay @dksung101 @LawrenceZLee @yiyao625

**Comment by erlend-sh** [comment]
Sure, give it a go :) this is a one-person job though, heh. (And github only lets us assign people who’ve replied to the thread)

**Comment by elliay** [comment]
We've never worked with rust before, so it will be a learning experience! Can you assign me as well? Thank you!

**Comment by MaxCWhitehead** [comment]
@elliay @reemhashir1 

Please let me know if you have questions after exploring how to run the game, how to add a sound effect, or play it from code. Looking at how the player jump is setup would be a good reference.

I think this is a definitely an accomplish-able task, but I would definitely expect you may have have questions - so please do ask if they come up. Happy to support.

The easiest place to ask questions would be on our discord (https://discord.com/invite/4smxjcheE5). Can ask in the "jumpy" channel, and optionally ping me `@max`. But communicating here is great too.

**Comment by reemhashir1** [comment]
Hey! We are currently deciding between two sounds for the character death. Please let me know which sound you approve of! Thank you for your quick responses. We truly appreciate it :) These are the links. 
https://pixabay.com/sound-effects/8-bit-video-game-fail-version-2-145478/

https://pixabay.com/sound-effects/8-bit-video-game-lose-sound-version-4-145477/

**Comment by reemhashir1** [comment]
I understand. How does this sound? https://freesound.org/people/brittmosel/sounds/529300/

**Comment by erlend-sh** [comment]
That one’s good!👍
