### ISSUE TITLE
In-Game Access to Controls Menu

### ISSUE THREAD

**Issue by r22222** [fishfolk/jumpy#999]
### Description

This feature request aims to enhance user accessibility within the game interface by allowing players to access the controls menu directly from within the gameplay screen. Currently, the controls menu can only be accessed from the main menu, which can disrupt the gameplay experience for new players who frequently need to refer to the controls scheme. By implementing this feature, players would have the convenience of checking the controls without having to navigate back to the main menu, thus improving overall user experience and reducing frustration during gameplay.

### Alternatives & Prior Art

Possible alternatives to implementing this feature could include adding a dedicated button or hotkey within the in-game interface to access the controls menu directly.

**Comment by MaxCWhitehead** [comment]
This is definitely an important one :) I think we already have an issue tracking this here: https://github.com/fishfolk/jumpy/issues/877
